---
name: ween_blaqe
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  animated_text_kit: ^4.2.2
#  draggable_widget: ^2.0.0
#  draggable_float_widget: ^0.1.0
  animations: ^2.0.7
  flutter_speed_dial: ^7.0.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.1
  colorful_safe_area: ^1.0.0
  photo_view: ^0.14.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  device_info_plus: ^9.0.3
  easy_localization: ^3.0.1
  firebase_auth: ^4.6.2
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.7
  firebase_ui_auth: ^1.6.4
  flutter_screenutil: ^5.9.0

  flame: ^1.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^9.0.0
  get: ^4.6.5
  go_router: ^9.0.0
  google_fonts: ^2.0.0
  google_sign_in: ^6.1.5
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: ^0.18.0
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  skeletons: ^0.0.3
  url_launcher: ^6.1.11
  vibration: ^1.8.3
dev_dependencies:
  flutter_lints: ^2.0.0

  #  fluttertoast: ^8.2.2
  flutter_test:
    sdk: flutter
  linter: null
flutter:
  uses-material-design: true
  assets:
    - assets/images/apartment_get_started.png
    - assets/images/another.jpeg
    - assets/images/apartments_images/
    - assets/images/apartments_images/about_apartment/
    - assets/images/apartments_images/advantages/
    - assets/images/whatsapp.png
    - assets/images/bottomNavBarIcon/apartment.png
    - assets/images/apartments_images/images_to_create_apartment/step_one.png
    - assets/images/apartments_images/images_to_create_apartment/step_two.png
    - assets/images/apartments_images/images_to_create_apartment/step_three.png
    - assets/images/apartments_images/images_to_create_apartment/step_four.png
    - assets/images/apartments_images/advantages/casino-cctv.png
    - assets/images/apartments_images/advantages/cctv.png
    - assets/images/apartments_images/advantages/cutlery1.png
    - assets/images/apartments_images/advantages/desktop.png
    - assets/images/apartments_images/advantages/dishes-washer.png
    - assets/images/gmail.png
    - assets/images/phone-call.png
    - assets/images/error_images/no network.png
    - assets/images/error_images/refresh.png
    - assets/images/error_images/search_not_found.png
    - assets/images/alert.png
    - assets/images/splash_screen.jpg
    - assets/images/correct.png
    - assets/I_will_delete_it/images/numbers/
    - assets/I_will_delete_it/images/family_members/
    - assets/I_will_delete_it/images/colors/
    - assets/I_will_delete_it/sounds/colors/
    - assets/I_will_delete_it/sounds/numbers/
    - assets/I_will_delete_it/sounds/family_members/
    - assets/I_will_delete_it/sounds/phrases/
    - assets/I_will_delete_it/images/weather_images/
    - assets/images/svg_images/tiktok_icons/
    - assets/images/svg_images/tiktok_icons/the_line.svg
    - assets/images/svg_images/tiktok_icons/Vector_home.svg
    - assets/images/svg_images/tiktok_icons/Ellipse 9 (Stroke).svg
    - assets/images/svg_images/tiktok_icons/Ellipse 10 (Stroke).svg
    - assets/images/svg_images/tiktok_icons/LIVE.svg
    - assets/images/svg_images/tiktok_icons/Vector.svg
    - assets/images/svg_images/tiktok_icons/discovery.png
    - assets/images/svg_images/tiktok_icons/Account Stroke Icon.svg
    - assets/images/svg_images/tiktok_icons/Message Stroke Icon.svg
    - assets/images/svg_images/tiktok_icons/add_of_tiktok_app_icon.svg
    - assets/images/svg_images/tiktok_icons/discovery.png
    - assets/images/svg_images/tiktok_icons/Home Solid Icon.svg
    - assets/images/apartments_images/apartment.jpg
    - assets/images/apartments_images/image1.png
    - assets/images/apartments_images/advantages/hot-water.png
    - assets/images/apartments_images/advantages/gas-stove.png
    - assets/images/apartments_images/advantages/first-aid-box.png
    - assets/images/apartments_images/advantages/kitchen-set.png
    - assets/images/apartments_images/advantages/microwave.png
    - assets/images/apartments_images/advantages/fire-extinguisher.png
    - assets/images/apartments_images/advantages/refrigerator-.png
    - assets/images/apartments_images/advantages/fire-alarm.png
    - assets/images/apartments_images/advantages/oven.png
    - assets/images/apartments_images/advantages/wifi.png
    - assets/images/apartments_images/advantages/plate.png
    - assets/images/svg_images/tiktok_icons/Like.svg
    - assets/images/svg_images/tiktok_icons/Share.svg
    - assets/images/svg_images/tiktok_icons/Disc.svg
    - assets/images/svg_images/tiktok_icons/Comments.svg
    - assets/images/svg_images/tiktok_icons/Bookmark.svg
    - assets/images/svg_images/tiktok_icons/Plus Button.svg
    - assets/images/svg_images/tiktok_icons/Left Arrow Icon.svg
    - assets/images/stop_war/b3.png
    - assets/images/stop_war/c1.jpeg
    - assets/images/stop_war/c2.jpg
    - assets/images/stop_war/c3.jpg
    - assets/images/stop_war/c4.jpg
    - assets/images/stop_war/c5.png
    - assets/images/stop_war/c7.png
    - assets/images/stop_war/b1.jpg
    - assets/images/stop_war/c6.png
    - assets/images/stop_war/b2.png
    - assets/images/tasbih.png
    - assets/images/mobile-development.png
    - assets/images/zzz_notifiction.png


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
    - family: IBM
      fonts:
        - asset: fonts/IBM/IBMPlexSansArabic-SemiBold.ttf
          weight: 700
    - family: TT Norms
      fonts:
        - asset: fonts/TT_Norms/TTNorms-Regular.otf
          weight: 800

fixed: false
ui:
  - null

flutter_assets:
  assets_path: assets/images
  output_path: lib/constants/
  filename: some_images.dart
  field_prefix: null
