---

name: ween_blaqe
description: A new Flutter project.
publish_to: none
version: 3.0.9
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
#  flutter_image_compress: ^2.3.0
  animated_text_kit: ^4.2.2
  get_it: ^7.6.7
  introduction_screen: ^3.1.14
  share_plus: ^10.0.2
  file_selector: ^1.0.3
  package_info_plus: ^8.0.2
  image: ^4.2.0
#  draggable_widget: ^2.0.0
#  draggable_float_widget: ^0.1.0
  animations: ^2.0.7
#  get_time_ago: ^2.0.0
  flutter_speed_dial: ^7.0.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.2.3
  carousel_slider_plus: ^7.0.0
#  cloud_firestore: ^4.9.1
  colorful_safe_area: ^1.0.0
  photo_view: ^0.15.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
#  device_info_plus: ^10.0.1
  easy_localization: ^3.0.1
#  firebase_auth: ^4.6.2
  permission_handler: ^11.3.1
  permission_handler_android: ^12.0.7
#  smooth_page_indicator: ^1.1.0
#  firebase_core: ^2.15.1
#  firebase_crashlytics: ^3.3.3
#  firebase_messaging: ^14.6.7
#  firebase_ui_auth: ^1.6.4
  flutter_screenutil: ^5.9.0
  favorite_button: ^0.0.4

  flame: ^1.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
#  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.7.0
  get: ^4.6.5
  upgrader: ^10.3.0
  go_router: ^13.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  http: ^0.13.5
  image_picker: ^1.0.8
  intl: ^0.19.0
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  skeletons: ^0.0.3
#  flutter_keyboard_visibility: ^5.4.1
  url_launcher: ^6.1.11
  intro_slider: ^4.2.1
  rename: ^3.0.1
  mime: ^1.0.3
  http_parser: ^4.0.2
  system_info_plus: ^0.0.6
  flutter_riverpod: ^2.6.1
  youtube_player_flutter: ^9.1.1
#  introduction_screen: ^3.1.12
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.1

  #  fluttertoast: ^8.2.2
  flutter_test:
    sdk: flutter
  linter: null
flutter_native_splash:
  color: "#2B2B2B"
  image: assets/images/icon_app.png
  android: true
  ios: true
  web: false
flutter:
  uses-material-design: true
  assets:
    - assets/images/apartments_images/
    - assets/images/apartments_images/about_apartment/
    - assets/images/whatsapp.png
    - assets/images/apartments_images/images_to_create_apartment/step_one.png
   # - assets/images/apartments_images/images_to_create_apartment
    #/second_step.png
    - assets/images/apartments_images/images_to_create_apartment/step_three.png
    - assets/images/apartments_images/images_to_create_apartment/second_step.png
    - assets/images/apartments_images/images_to_create_apartment/step_four.png
    - assets/images/tasbih.png
    - assets/images/error_images/no network.png
#    - assets/images/error_images/search_not_found.png
    - assets/images/apartments_images/apartment.jpg
    - assets/images/mobile-development.png
    - assets/images/apartments_images/Simulator Screenshot - iPhone 15 Pro Max - 2023-12-05 at 14.27.36.png
    - assets/images/apartments_images/Simulator Screenshot - iPhone 15 Pro Max - 2023-12-05 at 14.32.35.png
    - assets/images/apartments_images/Simulator Screenshot - iPhone 15 Pro Max - 2023-12-05 at 14.48.13.png
    - assets/images/splash screen heigh qulity with large size.png
#    - assets/images/error_images/search_not_found_dark_mode.png
    - assets/images/error_images/not_found_dark_mode.png
    - assets/images/error_images/not_found_light_mode.png
    - assets/images/intro_images/intro_screen2.png
    - assets/images/intro_images/splash_screen3.png
    - assets/images/intro_images/splash_screen4.png
    - assets/images/intro_images/splash_screen5.png
    - assets/images/intro_images/splash_screen6.png
    - assets/images/gmail.png
    - assets/images/apartments_images/images_to_create_apartment/first_setp_dark_mode.png
    - assets/images/apartments_images/images_to_create_apartment/thrid_setp_dark_mode.png
    - assets/images/apartments_images/images_to_create_apartment/fourth_step_dark_mode.png
    - assets/images/apartments_images/images_to_create_apartment/second_step_dark_mode.png
  #- assets/images/apartment_images/apartments_images/second_step_dark_mode.png
    - assets/languages/en.json
    - assets/languages/ar.json











  fonts:
#    - family: Cairo
#      fonts:
#        - asset: fonts/Cairo/Cairo-SemiBold.ttf
#    - family: IBM
#      fonts:
#        - asset: fonts/IBM/IBMPlexSansArabic-Bold.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-ExtraLight.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-Light.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-Medium.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-Regular.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-SemiBold.ttf
#        - asset: fonts/IBM/IBMPlexSansArabic-Thin.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/static/Cairo-Black.ttf
        - asset: fonts/Cairo/static/Cairo-Bold.ttf
        - asset: fonts/Cairo/static/Cairo-ExtraBold.ttf
        - asset: fonts/Cairo/static/Cairo-ExtraLight.ttf
        - asset: fonts/Cairo/static/Cairo-Light.ttf
        - asset: fonts/Cairo/static/Cairo-Medium.ttf
        - asset: fonts/Cairo/static/Cairo-Regular.ttf
        - asset: fonts/Cairo/static/Cairo-SemiBold.ttf
        - asset: fonts/Cairo/Cairo-VariableFont_slnt,wght.ttf















#    - family: TT Norms
#      fonts:
#        - asset: fonts/TT_Norms/TTNorms-Regular.otf
#          weight: 800

fixed: false
ui:
  - null

flutter_assets:
  assets_path: assets/images
  output_path: lib/constants/
  filename: some_images.dart
  field_prefix: null
