// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDl1ZiLBWTWDJ8KkGDlZIOzN9YUd4nTlPc',
//     appId: '1:340084591875:web:38ed9bc64d4e068f7aad36',
//     messagingSenderId: '340084591875',
//     projectId: 'weenblaqedatabase',
//     authDomain: 'weenblaqedatabase.firebaseapp.com',
//     storageBucket: 'weenblaqedatabase.appspot.com',
//     measurementId: 'G-0CGKVDXV8P',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCq0WXj7dCEQSk43gmCcabm7vqqKkBLXl0',
//     appId: '1:493735129801:android:5f6a78258f9bf3b5fdd318',
//     messagingSenderId: '493735129801',
//     projectId: 'weenbalaqee-8e483',
//     storageBucket: 'weenbalaqee-8e483.firebasestorage.app',
//   );
//
// //
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBtIS7c8fm_OQ0X_ZVAIWUbibxdJdnUqBQ',
//     appId: '1:493735129801:ios:b194c03e3e103055fdd318',
//     messagingSenderId: '493735129801',
//     projectId: 'weenbalaqee-8e483',
//     storageBucket: 'weenbalaqee-8e483.firebasestorage.app',
//     iosBundleId: 'com.example.weenBlaqe',
//   );
// }
