// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDl1ZiLBWTWDJ8KkGDlZIOzN9YUd4nTlPc',
//     appId: '1:340084591875:web:38ed9bc64d4e068f7aad36',
//     messagingSenderId: '340084591875',
//     projectId: 'weenblaqedatabase',
//     authDomain: 'weenblaqedatabase.firebaseapp.com',
//     storageBucket: 'weenblaqedatabase.appspot.com',
//     measurementId: 'G-0CGKVDXV8P',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBMWiZBG41Yc7lcg3AbXttea_ayrI4nxTQ',
//     appId: '1:340084591875:android:d0e35c56276e44267aad36',
//     messagingSenderId: '340084591875',
//     projectId: 'weenblaqedatabase',
//     storageBucket: 'weenblaqedatabase.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCrYYK83OfAJRmSD-WhNFedzOGV_pr9xpw',
//     appId: '1:340084591875:ios:f51e1deef98854407aad36',
//     messagingSenderId: '340084591875',
//     projectId: 'weenblaqedatabase',
//     storageBucket: 'weenblaqedatabase.appspot.com',
//     iosClientId: '340084591875-qmthcuslemtm43q955crdk0r7re0dsmp.apps.googleusercontent.com',
//     iosBundleId: 'com.example.weenBlaqe',
//   );
// }
